# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(682, 470)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 571, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 110, 574, 141))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_key = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_key.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_key.sizePolicy().hasHeightForWidth())
        self.pushButton_key.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_key.setFont(font)
        self.pushButton_key.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_key.setObjectName(_fromUtf8("pushButton_key"))
        self.horizontalLayout_2.addWidget(self.pushButton_key)
        self.pushButton_run = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_2.addWidget(self.pushButton_run)
        self.pushButton_result = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_result.sizePolicy().hasHeightForWidth())
        self.pushButton_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_result.setFont(font)
        self.pushButton_result.setObjectName(_fromUtf8("pushButton_result"))
        self.horizontalLayout_2.addWidget(self.pushButton_result)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 280, 571, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 4, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 3, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 2, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 4, 2, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 2, 2, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 4, 1, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 3, 3, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout.addWidget(self.checkBox_14, 3, 4, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 3, 2, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 2, 3, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 2, 4, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 4, 3, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout.addWidget(self.checkBox_15, 4, 4, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout.addWidget(self.checkBox_16, 2, 5, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout.addWidget(self.checkBox_17, 3, 5, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout.addWidget(self.checkBox_18, 4, 5, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(260, 370, 211, 57))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.progressBar = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_2.addWidget(self.progressBar_2, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 370, 101, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 370, 131, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.progressBar_3 = QtGui.QProgressBar(Dialog)
        self.progressBar_3.setGeometry(QtCore.QRect(40, 410, 111, 16))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton_result, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "视频搜索", None))
        self.label.setText(_translate("Dialog", "视频搜索程序", None))
        self.pushButton_key.setText(_translate("Dialog", "关键词", None))
        self.pushButton_run.setText(_translate("Dialog", "运行", None))
        self.pushButton_result.setText(_translate("Dialog", "结果", None))
        self.checkBox_2.setText(_translate("Dialog", "爱奇艺", None))
        self.checkBox_5.setText(_translate("Dialog", "腾讯视频", None))
        self.checkBox.setText(_translate("Dialog", "优酷", None))
        self.checkBox_4.setText(_translate("Dialog", "新浪视频", None))
        self.checkBox_3.setText(_translate("Dialog", "土豆", None))
        self.checkBox_9.setText(_translate("Dialog", "风行", None))
        self.checkBox_7.setText(_translate("Dialog", "乐视", None))
        self.checkBox_6.setText(_translate("Dialog", "搜狐视频", None))
        self.checkBox_10.setText(_translate("Dialog", "暴风影音", None))
        self.checkBox_14.setText(_translate("Dialog", "酷6", None))
        self.checkBox_8.setText(_translate("Dialog", "华数", None))
        self.checkBox_11.setText(_translate("Dialog", "响巢看看", None))
        self.checkBox_13.setText(_translate("Dialog", "56网", None))
        self.checkBox_12.setText(_translate("Dialog", "PPTV", None))
        self.checkBox_15.setText(_translate("Dialog", "爆米花", None))
        self.checkBox_16.setText(_translate("Dialog", "TV89", None))
        self.checkBox_17.setText(_translate("Dialog", "央视网", None))
        self.checkBox_18.setText(_translate("Dialog", "芒果TV", None))
        self.label_2.setText(_translate("Dialog", "单个平台", None))
        self.label_3.setText(_translate("Dialog", "所有平台", None))
        self.pushButton.setText(_translate("Dialog", "平台搜索", None))
        self.pushButton_2.setText(_translate("Dialog", "百度搜索", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

